"""initial schema

Revision ID: 05cb0d50e6ad
Revises:
Create Date: 2026-09-06 11:48:41.647064

Transcribed from docs/plan.md §2. Hand-written rather than autogenerated so
the DDL (ltree, pgvector, generated tsvector column, HNSW index) matches the
design doc exactly.
"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "05cb0d50e6ad"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS ltree")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    op.execute(
        """
        CREATE TABLE projects (
            id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            name        TEXT NOT NULL,
            description TEXT,
            created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )

    op.execute("CREATE TYPE doc_format AS ENUM ('pdf', 'docx', 'pptx', 'txt', 'md')")
    op.execute(
        "CREATE TYPE doc_status AS ENUM ('uploaded', 'extracting', 'awaiting_review', "
        "'indexing', 'ready', 'failed')"
    )

    op.execute(
        """
        CREATE TABLE documents (
            id              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            sha256          CHAR(64) NOT NULL UNIQUE,
            title           TEXT NOT NULL,
            author          TEXT,
            format          doc_format NOT NULL,
            original_name   TEXT NOT NULL,
            storage_path    TEXT NOT NULL,
            raw_text        TEXT,
            status          doc_status NOT NULL DEFAULT 'uploaded',
            page_offset     INT NOT NULL DEFAULT 0,
            created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )

    op.execute(
        """
        CREATE TABLE project_documents (
            project_id  BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
            document_id BIGINT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
            added_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
            PRIMARY KEY (project_id, document_id)
        )
        """
    )

    op.execute("CREATE TYPE structure_source AS ENUM ('detected', 'manual')")

    op.execute(
        """
        CREATE TABLE sections (
            id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            document_id   BIGINT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
            path          LTREE NOT NULL,
            title         TEXT NOT NULL,
            display_path  TEXT NOT NULL,
            depth         INT  NOT NULL,
            ordinal       INT  NOT NULL,
            char_start    INT  NOT NULL,
            char_end      INT  NOT NULL,
            source        structure_source NOT NULL DEFAULT 'detected',
            UNIQUE (document_id, path)
        )
        """
    )
    op.execute("CREATE INDEX sections_path_gist ON sections USING GIST (path)")
    op.execute("CREATE INDEX sections_doc       ON sections (document_id)")

    op.execute(
        """
        CREATE TABLE chunks (
            id           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            document_id  BIGINT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
            section_id   BIGINT NOT NULL REFERENCES sections(id)  ON DELETE CASCADE,
            ordinal      INT NOT NULL,
            text         TEXT NOT NULL,
            embed_text   TEXT NOT NULL,
            char_start   INT NOT NULL,
            char_end     INT NOT NULL,
            token_count  INT NOT NULL,
            embedding    VECTOR(1024),
            tsv          TSVECTOR GENERATED ALWAYS AS (to_tsvector('english', text)) STORED
        )
        """
    )
    op.execute(
        "CREATE INDEX chunks_embedding ON chunks "
        "USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64)"
    )
    op.execute("CREATE INDEX chunks_tsv     ON chunks USING GIN (tsv)")
    op.execute("CREATE INDEX chunks_doc     ON chunks (document_id)")
    op.execute("CREATE INDEX chunks_section ON chunks (section_id)")

    op.execute(
        """
        CREATE TABLE section_summaries (
            id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            section_id  BIGINT NOT NULL REFERENCES sections(id) ON DELETE CASCADE,
            document_id BIGINT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
            summary     TEXT NOT NULL,
            embedding   VECTOR(1024),
            model       TEXT NOT NULL,
            created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
            UNIQUE (section_id)
        )
        """
    )
    op.execute(
        "CREATE INDEX summaries_embedding ON section_summaries "
        "USING hnsw (embedding vector_cosine_ops)"
    )

    op.execute(
        """
        CREATE TABLE embedding_runs (
            id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            model       TEXT NOT NULL,
            dimension   INT  NOT NULL,
            started_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
            is_current  BOOLEAN NOT NULL DEFAULT TRUE
        )
        """
    )
    op.execute(
        "ALTER TABLE chunks ADD COLUMN embedding_run_id BIGINT REFERENCES embedding_runs(id)"
    )

    op.execute(
        """
        CREATE TABLE ingest_jobs (
            id           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            document_id  BIGINT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
            stage        TEXT NOT NULL,
            progress     REAL NOT NULL DEFAULT 0,
            error        TEXT,
            started_at   TIMESTAMPTZ,
            finished_at  TIMESTAMPTZ
        )
        """
    )

    op.execute(
        """
        CREATE TABLE conversations (
            id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
            title      TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )

    op.execute(
        """
        CREATE TABLE messages (
            id              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
            role            TEXT NOT NULL,
            content         TEXT NOT NULL,
            created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )

    op.execute(
        """
        CREATE TABLE message_citations (
            message_id BIGINT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
            chunk_id   BIGINT NOT NULL REFERENCES chunks(id)   ON DELETE CASCADE,
            rank       INT NOT NULL,
            PRIMARY KEY (message_id, chunk_id)
        )
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS message_citations")
    op.execute("DROP TABLE IF EXISTS messages")
    op.execute("DROP TABLE IF EXISTS conversations")
    op.execute("DROP TABLE IF EXISTS ingest_jobs")
    op.execute("DROP TABLE IF EXISTS embedding_runs CASCADE")
    op.execute("DROP TABLE IF EXISTS section_summaries")
    op.execute("DROP TABLE IF EXISTS chunks")
    op.execute("DROP TABLE IF EXISTS sections")
    op.execute("DROP TYPE IF EXISTS structure_source")
    op.execute("DROP TABLE IF EXISTS project_documents")
    op.execute("DROP TABLE IF EXISTS documents")
    op.execute("DROP TYPE IF EXISTS doc_status")
    op.execute("DROP TYPE IF EXISTS doc_format")
    op.execute("DROP TABLE IF EXISTS projects")
